In [ ]:
memory = []

In [1]:
import numpy as np
import torch
import gym

In [2]:
import gym
from torch import nn, optim
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy

In [3]:
import random

In [54]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [50]:
device = "cpu"

In [7]:
env = gym.make('LunarLander-v2')
env.seed(5)
print('State shape: ', env.observation_space)
print('Number of Actions: ', env.action_space)

State shape:  Box(-inf, inf, (8,), float32)
Number of Actions:  Discrete(4)


In [5]:
memry = []

In [19]:
# state = torch.from_numpy(env.reset()).to(device)
action = 2
state = env.reset()
next_state, reward, done, data = env.step(action)
reward = np.array([reward],dtype = float)
action = np.array([action],dtype = int)
done = np.array([done],dtype = int)
# reward = torch.from_numpy(np.array([reward])).to(device)
# action = torch.from_numpy(np.array([action])).to(device)
# next_state = torch.from_numpy(next_state).to(device)
transition = (state,action,reward,next_state,done)
transition
memry.append(transition)

In [ ]:
Z = random.sample(memry, k=2)
Z

In [ ]:
torch.tensor(np.array(Z,dtype = float))

In [ ]:
X = [row[4] for row in Z]
X

In [ ]:
X = [row[0] for row in Z]
X

In [ ]:
torch.tensor(np.array(X,dtype = float))

In [ ]:
X[0]+X[1]

In [ ]:
Z = np.array(Z,dtype = object)
Z.shape

In [ ]:
Z = Z.T
Z.shape

In [ ]:
Z[0]

In [ ]:
Z[1]

In [ ]:
Z[2]+Z[3]

In [ ]:
Z[0] + Z[1]

In [ ]:
Z[2]

In [ ]:
torch.as_tensor(Z[2])

In [20]:
C = random.sample(memry, k=10)

In [ ]:
C

In [21]:
C = np.array(C,dtype = object)

In [ ]:
C

In [22]:
C = C.T

In [ ]:
C

In [23]:
C = C.tolist()

In [55]:
states = torch.tensor(C[0]).to(device)

In [84]:
C[0]

[array([ 0.00584612,  1.4083513 ,  0.59213126, -0.11418455, -0.00676737,
        -0.1341265 ,  0.        ,  0.        ], dtype=float32),
 array([-0.00407314,  1.4067007 , -0.41257963, -0.18753307,  0.00472654,
         0.09345536,  0.        ,  0.        ], dtype=float32),
 array([-0.00475454,  1.4089692 , -0.48160577, -0.08671539,  0.00551617,
         0.10909085,  0.        ,  0.        ], dtype=float32),
 array([-0.00763311,  1.4082026 , -0.77316105, -0.12081107,  0.0088516 ,
         0.1751325 ,  0.        ,  0.        ], dtype=float32),
 array([ 1.1624336e-03,  1.3995911e+00,  1.1772464e-01, -5.0350881e-01,
        -1.3401622e-03, -2.6666407e-02,  0.0000000e+00,  0.0000000e+00],
       dtype=float32),
 array([-0.00511417,  1.4096055 , -0.51803106, -0.05844457,  0.00593287,
         0.11734165,  0.        ,  0.        ], dtype=float32),
 array([ 0.00542307,  1.4186835 ,  0.5492875 ,  0.34503332, -0.00627724,
        -0.12442194,  0.        ,  0.        ], dtype=float32),
 array([-0

In [31]:
env = gym.make('LunarLander-v2')
env.seed(5)
print('State shape: ', env.observation_space)
print('Number of Actions: ', env.action_space)

State shape:  Box(-inf, inf, (8,), float32)
Number of Actions:  Discrete(4)


In [46]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.seed = torch.manual_seed(5)
        self.fc1 = nn.Linear(8, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 4)
    
    def forward(self, state):
        h = F.relu(self.fc1(state))
        h = F.relu(self.fc2(h))
        y = self.fc3(h)
        return y

In [56]:
m = Network()
m.cuda()

c = m(states)

c


tensor([[-0.0643, -0.0962,  0.0494,  0.0027],
        [-0.0687, -0.1367,  0.0091, -0.0330],
        [-0.0679, -0.1333,  0.0033, -0.0301],
        [-0.0660, -0.1424, -0.0113, -0.0464],
        [-0.0772, -0.1363,  0.0390, -0.0201],
        [-0.0676, -0.1330,  0.0008, -0.0309],
        [-0.0648, -0.0906,  0.0510,  0.0149],
        [-0.0698, -0.1395,  0.0175, -0.0326],
        [-0.0678, -0.1337,  0.0116, -0.0261],
        [-0.0684, -0.1166,  0.0376, -0.0106]], device='cuda:0',
       grad_fn=<AddmmBackward>)

In [132]:
m.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.2335, -0.2644,  0.2881,  ..., -0.2711, -0.2373,  0.1682],
                      [-0.3300,  0.3494,  0.0753,  ...,  0.1127,  0.1520,  0.0561],
                      [ 0.3401,  0.1062, -0.3135,  ..., -0.1687, -0.3248,  0.2016],
                      ...,
                      [ 0.0593, -0.1358, -0.1670,  ..., -0.2488,  0.0943, -0.2922],
                      [-0.0329, -0.1998, -0.1133,  ..., -0.0580,  0.3441, -0.3245],
                      [-0.2374, -0.0910,  0.0216,  ...,  0.1318,  0.1261, -0.1168]],
                     device='cuda:0')),
             ('fc1.bias',
              tensor([ 0.2725, -0.0297,  0.0205,  0.0226,  0.0591,  0.0419,  0.0767, -0.2454,
                      -0.1971,  0.1539,  0.0453, -0.2112, -0.1418, -0.3296, -0.1335, -0.0301,
                       0.0770, -0.1620, -0.0279, -0.0841, -0.2585, -0.0114, -0.1138, -0.2772,
                      -0.2598,  0.2007,  0.2991, -0.2293, -0.0895, -0.0738,  0.1431, -0.1166

In [131]:
for i,j in zip(m.parameters()):
    print(i.data)

TypeError: 'method' object is not iterable

Note : Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm) ( This error comes up if states is in cpu mode) 

In [80]:
Qmax = c.detach()

In [100]:
jk = Qmax.max(1)[0].unsqueeze(1)
jk

tensor([[ 0.0494],
        [ 0.0091],
        [ 0.0033],
        [-0.0113],
        [ 0.0390],
        [ 0.0008],
        [ 0.0510],
        [ 0.0175],
        [ 0.0116],
        [ 0.0376]], device='cuda:0')

In [92]:
np.array(C[2])

array([[-0.68292068],
       [ 0.54032564],
       [-1.4585829 ],
       [-0.01305273],
       [ 1.38880443],
       [-1.17071132],
       [-2.35570871],
       [ 0.47246154],
       [ 2.22941799],
       [ 2.27439815]])

In [96]:
c1 = 0*jk

In [117]:
c4 = torch.tensor(C[4]).to(device)
c3 = torch.tensor(C[2],dtype = torch.float).to(device)

In [118]:
c3

tensor([[-0.6829],
        [ 0.5403],
        [-1.4586],
        [-0.0131],
        [ 1.3888],
        [-1.1707],
        [-2.3557],
        [ 0.4725],
        [ 2.2294],
        [ 2.2744]], device='cuda:0')

In [116]:
torch.where(c4>0,c1,c3)

RuntimeError: expected scalar type float but found double

In [124]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = zip(a, b)

In [125]:
for i,j in x:
    print(i)

John
Charles
Mike


In [19]:
random.choice(np.arange(4))

3

In [20]:
np.random.randint(0,4)

3

In [23]:
float(5e-4)


0.0005